# Generated by Django 5.1.2 on 2025-01-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMapp', '0002_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('subdomains', models.TextField()),
                ('scan_results', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASMapp.user')),
            ],
        ),
    ]
