# Generated by Django 5.1.2 on 2025-04-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMapp', '0005_apikey_useractivity_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
