# Generated by Django 5.1.2 on 2025-04-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMapp', '0007_userfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='weekly_digest',
            new_name='completed_onboarding',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='critical_alerts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ASMapp.user'),
        ),
    ]
