# Generated by Django 5.1.2 on 2025-05-03 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMapp', '0012_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='nucleiresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vulnerability Scan Result', 'verbose_name_plural': 'Vulnerability Scan Results'},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Domain Scan Result', 'verbose_name_plural': 'Domain Scan Results'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
