# Generated by Django 5.1.2 on 2025-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMapp', '0013_alter_userfeedback_user_alter_apikey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_via_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_via_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slack_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
